Repository guibranco/BancosBrasileiros, pull requests merged in 2023-08, with the labels that each got.

#275 [Snyk] Upgrade bancos-brasileiros from 4.0.206 to 4.0.207
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S

#276 [Snyk] Upgrade bancos-brasileiros from 4.0.207 to 4.0.210
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S

#278 [Snyk] Upgrade bancos-brasileiros from 4.0.210 to 4.0.218
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S

#279 [Snyk] Upgrade bancos-brasileiros from 4.0.218 to 4.0.220
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S

#280 [Snyk] Upgrade bancos-brasileiros from 4.0.220 to 4.0.233
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S

#281 [Snyk] Upgrade bancos-brasileiros from 4.0.233 to 5.0.6
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S

#282 [Snyk] Upgrade bancos-brasileiros from 5.0.6 to 5.0.8
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S

#284 [Snyk] Upgrade bancos-brasileiros from 5.0.8 to 5.0.9
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S

#287 Update size-label.yml
  .github/workflows/size-label.yml
Labels: size/S

#288 Create lint-csharp.yml
  .config/dotnet-tools.json
  .github/workflows/lint-csharp.yml
Labels: size/M

#285 [Snyk] Upgrade bancos-brasileiros from 5.0.9 to 5.0.12
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S

#286 Implementado filtro de busca baseado nos 3 dígitos do código COMPE - Examplo .NET
  examples/dotnet/Program.cs
Labels: examples, size/M, .NET

#289 [Snyk] Upgrade bancos-brasileiros from 5.0.12 to 5.0.13
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S

#290 Linter
  examples/dotnet/Program.cs
  schemas/csharp.cs
Labels: size/S

#292 Update schema.sql
  schemas/schema.sql
Labels: sql, schema

#296 Update request-new-bank.md
  .github/ISSUE_TEMPLATE/request-new-bank.md
Labels: size/XS

#298 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/S

#300 [Snyk] Upgrade bancos-brasileiros from 5.0.13 to 5.0.14
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S

#303 Use mergetool from dedicated repository
  .github/dependabot.yml
  .github/workflows/codacy-security-scan.yml
  .github/workflows/contributors-readme.yml
  .github/workflows/daily-updates.yml
Labels: enhancement, dependencies, github_actions, documentation, size/M, .NET, Code Quality
