Repository guibranco/BancosBrasileiros, pull requests merged in 2024-11, with the labels that each got.

#584 [Snyk] Upgrade bancos-brasileiros from 6.0.93 to 6.0.94
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S, ☑️ auto-merge

#588 [Snyk] Upgrade bancos-brasileiros from 6.0.94 to 6.0.97
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: size/S, ☑️ auto-merge

#582 Adição de um novo método IsValidCompe no arquivo Program.cs
  examples/dotnet/Program.cs
Labels: size/S

#594 Fix outdated links
  .lycheeignore
  data/bancos.csv
  data/bancos.json
  data/bancos.md
  data/bancos.sql
  data/bancos.xml
Labels: enhancement, size/S, hacktoberfest, ☑️ auto-merge, Review effort [1-5]: 2, 🐛 bug, 🔗 link checker, documentation
