Repository guibranco/BancosBrasileiros, pull requests merged in 2024-09, with the labels that each got.

#503 Upgrade bancos-brasileiros from 6.0.49 to 6.0.51
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: enhancement, ☑️ auto-merge, Review effort [1-5]: 1

#510 Enhance C# example code for readability and functionality
  examples/dotnet/ConsoleApp.csproj
  examples/dotnet/Program.cs
Labels: enhancement, dependencies, examples, size/M, .NET, Code Quality, Review effort [1-5]: 2

#521 Enhance link checker with updated bank URLs
  .lycheeignore
  data/bancos.csv
  data/bancos.json
  data/bancos.md
  data/bancos.sql
Labels: enhancement, help wanted, good first issue, size/S, hacktoberfest, ☑️ auto-merge, Review effort [1-5]: 2, 🐛 bug, 🔗 link checker

#525 Enhance link checker and update bank data
  .lycheeignore
  data/bancos.csv
  data/bancos.json
  data/bancos.md
  data/bancos.sql
Labels: enhancement, help wanted, good first issue, size/S, hacktoberfest, ☑️ auto-merge, Review effort [1-5]: 2, 🐛 bug, 🔗 link checker, 🚦 awaiting triage

#529 Enhance link-checker workflow for pull request reporting
  .github/workflows/link-checker.yml
Labels: enhancement, help wanted, good first issue, github-actions, size/S, CI, Code Quality, hacktoberfest, ☑️ auto-merge, Review effort [1-5]: 2, 🐛 bug, 🔗 link checker

#532 Update bank URLs in bancos.json
  data/bancos.json
Labels: enhancement, help wanted, good first issue, size/S, hacktoberfest, ☑️ auto-merge, Review effort [1-5]: 2, 🐛 bug, 🔗 link checker

#537 Upgrade bancos-brasileiros from 6.0.51 to 6.0.62
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 1

#541 Enhance .lycheeignore for improved domain management
  .lycheeignore
Labels: enhancement, help wanted, good first issue, size/M, hacktoberfest, ☑️ auto-merge, Review effort [1-5]: 2, 🐛 bug, 🔗 link checker, 🚦 awaiting triage

#542 Remove Pull Request Template from GitHub Configuration
  .github/pull_request_template.md
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 1

#544 Update .lycheeignore to include github.com/ghost
  .lycheeignore
Labels: enhancement, help wanted, good first issue, size/XS, hacktoberfest, ☑️ auto-merge, Review effort [1-5]: 1, 🐛 bug, 🔗 link checker

#548 Upgrade bancos-brasileiros from 6.0.62 to 6.0.67
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 1

#550 Enhance link checker report with updated URLs and formatting
  data/bancos.csv
  data/bancos.json
  data/bancos.md
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2
