Repository guibranco/BancosBrasileiros, pull requests merged in 2025-07, with the labels that each got.

#758 Fix link checker report
  .lycheeignore
  README.md
  README.pt-br.md
Labels: enhancement, size/XS, hacktoberfest, ☑️ auto-merge, Review effort [1-5]: 2, 🐛 bug, 🔗 link checker, 🚦 awaiting triage, documentation

#759 [Snyk] Upgrade bancos-brasileiros from 6.2.21 to 6.2.28
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 1

#765 [Snyk] Upgrade bancos-brasileiros from 6.2.28 to 6.2.32
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 1

#766 Action to generate dto automatically when bancos.json is updated
  .github/workflows/generate-dto.yml
Labels: enhancement, 📦 dependencies, examples, :octocat: github-actions, 📝 documentation, size/M, CI, Code Quality, schema, hacktoberfest, gitauto, Review effort [1-5]: 2, 🚦 awaiting triage

#767 Update version
  Cargo.toml
  README.md
  appveyor.yml
  composer.json
  package-lock.json
  package.json
  pubspec.yaml
  setup.py
Labels: enhancement, size/L, ☑️ auto-merge, Review effort [1-5]: 2, documentation

#768 Update workflows
  .githooks/prepare-commit-msg
  .github/workflows/codacy-security-scan.yml
  .github/workflows/contributors-readme.yml
  .github/workflows/daily-updates.yml
  .github/workflows/generate-dto.yml
  .github/workflows/health-check.yml
  .github/workflows/infisical-secrets-check.yml
  .github/workflows/label-issue.yml
  .github/workflows/link-checker.yml
  .github/workflows/lint-csharp.yml
  .github/workflows/lint-php.yml
  .github/workflows/size-label.yml
  .github/workflows/sonar-cloud.yml
  .github/workflows/update-abbreviations.yml
  data/bancos.xml
  examples/dotnet/ConsoleApp.csproj
  schemas/schema.xml
Labels: enhancement, size/XXL, ☑️ auto-merge, documentation, Review effort [1-5]: 4

#769 [Snyk] Upgrade bancos-brasileiros from 6.2.32 to 6.2.35
  examples/emberjs/package-lock.json
  examples/emberjs/package.json
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 1
